run:
  timeout: 5m
  modules-download-mode: vendor
  skip-dirs:
    - store/storetest/mocks

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - golint
    - gosimple
    - govet
    - ineffassign
    - scopelint
    - structcheck
    - staticcheck
    - unconvert
    - unused
    - varcheck
    - misspell
    - goimports
    # TODO: enable this later
    # - errcheck

issues:
  exclude-rules:
    - linters:
      # ignore unused warnings from enterprise code
      # add more as required.
      - unused
      text: "SetupEnterprise"

    - linters:
      - scopelint
      # ignore warnings from table tests. https://github.com/kyoh86/scopelint/issues/4
      path: ".*_test.go|store/storetest"

    - linters:
      - staticcheck
      path: ".*_test.go|store/storetest"

    - linters:
      - golint
      text: "should have|should be|should replace|stutters|underscore|annoying|error strings should not be capitalized"

    - linters:
      - golint
      path: "model/"

    - linters:
      - misspell
      path: "utils/markdown/html_entities.go"

    - linters:
      - unparam
      path: "app/plugin_api_tests"
      text: "is always nil"
